Initial ui
mjgardner/project2 pull request #5
Opened 2019-03-25 13:43 UTC by moonejon

2019-03-25 14:53 UTC, mjgardner requested changes
See my inline comments

2019-03-25 14:53 UTC, mjgardner commented on views/index.handlebars
> +                <h5 class="Idea Details" id="exampleModalCenterTitle">Modal title</h5>
Are these the right classes for this header? Also, "Modal title" sounds pretty generic.

2019-03-25 14:53 UTC, mjgardner commented on views/index.handlebars
> +                    <label for="example-text">Example Text</label>
Again, a generic label. "Example Text"?

2019-03-25 14:53 UTC, mjgardner commented on views/index.handlebars
> +                    <label for="example-description">Example Description</label>
Generic label

2019-03-25 14:53 UTC, mjgardner commented on views/layouts/main.handlebars
> +  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
I think we're going to need the full jQuery for the AJAX stuff.

2019-03-25 14:53 UTC, mjgardner commented on views/index.handlebars
> +                <a class="nav-link" href="#">Trending</a>
Is this eventually going to a separate page?

2019-03-25 16:30 UTC, moonejon commented on views/index.handlebars
> +                <h5 class="Idea Details" id="exampleModalCenterTitle">Modal title</h5>
the classes are correct, i believe. Those are bootstrap classes. The generic example text stuff is stuff that I need to replace. I'll do that this evening.

2019-03-25 16:30 UTC, moonejon commented on views/layouts/main.handlebars
> +  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
Very true... forgot about that

2019-03-25 16:31 UTC, moonejon commented on views/index.handlebars
> +                <a class="nav-link" href="#">Trending</a>
Yes, it is.

2019-03-25 23:18 UTC, mjgardner commented on views/index.handlebars
> +                <h5 class="Idea Details" id="exampleModalCenterTitle">Modal title</h5>
It's hidden by a scrollbar in GitHub's review interface, but I was asking about the `<h5 class="Idea Details" ...>` classes.

2019-03-25 23:19 UTC, moonejon commented on views/index.handlebars
> +                <h5 class="Idea Details" id="exampleModalCenterTitle">Modal title</h5>
Nope... that was a mistake I made when I was tired. Thanks for catching that.

2019-03-27 00:11 UTC, mjgardner approved these changes

2019-03-27 00:11 UTC, merged